exclude: |
    (?x)^(
        notebooks/GTS_Totals_weather_act.ipynb|
        notebooks/IOOS_BTN.ipynb|
        btn_metrics.py|
        gts_atn_metrics.py|
        read_bufr.py|
        website/.*
    )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.yaml
          )$
      args:
        - --ignore-words-list=pres,noo

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]
    - id: ruff-format

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.5
  hooks:
    - id: nbqa-check-ast
    - id: nbqa-black
    - id: nbqa-ruff
      args: [
        --fix,
        --config=ruff.toml,
        ]

- repo: https://github.com/bdice/nb-strip-paths
  rev: v0.1.0
  hooks:
    - id: nb-strip-paths

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
