target-version = "py312"
lint.select = ["ALL"]
line-length = 120
exclude = [
    "website/*",
    "read_bufr.py",
    "btn_metrics.py",
    "gts_atn_metrics.py",
    "gts_regional_metrics.py",
]

lint.ignore = [
    "ANN001",  # Missing type annotation for function argument
    "ANN201",  # Missing return type annotation for public function
    "D203",  # 1 blank line required before class docstring
    "D205",  # 1 blank line required between summary line and description
    "D213",  # incompatible. Ignoring `multi-line-summary-second-line`
    "D401",  # First line of docstring should be in imperative mood
    "G004",  # logging-f-string
    "PD901",  # Avoid using the generic variable name `df` for DataFrames
    "ISC001",  # single-line-implicit-string-concatenation
    "COM812",  # missing-trailing-comma
    ]

[lint.extend-per-file-ignores]
"test_*.py" = [
    "S101",  # Use of assert detected
    "D103",  # Missing docstring in public function
    "INP001",  # File is part of an implicit namespace package
]
# nbqa-ruff acts on converted .py so we cannot glob .ipynb :-/
# https://github.com/nbQA-dev/nbQA/issues/823
"run_metrics*" = [
    "INP001",  # is part of an implicit namespace package
    "D100",  # Missing docstring in public module
    "E402",  # Module level import not at top of file
    "FBT003",  # Boolean positional value in function call
    "T201",  # `print` found"
]
"glider_metrics*" = [
    "ANN001",  # Missing type annotation for function argument
    "ANN202", # Missing return type annotation for private function
    "ANN201",  # Missing return type annotation for public function
    "B018",  # Found useless expression. Either assign it to a variable or remove it
    "D100",  # Missing docstring in public module
    "D103",  # Missing docstring in public function
    "E402",  # Module level import not at top of file
    "ERA001",  # Found commented-out code
    "FBT003",  # Boolean positional value in function call
    "INP001",  # File is part of an implicit namespace package
    "PD901",  # Avoid using the generic variable name `df` for DataFrames
    "S603",  # `subprocess` call: check for execution of untrusted input
    "T201",  # `print` found"
]
[lint.pycodestyle]
max-doc-length = 180
