name: Full Tests

on:
  pull_request:
  push:
    branches: [main]

# no permissions by default
permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0
      with:
        manifest-path: pyproject.toml

    - name: Tests
      shell: bash -l {0}
      run: |
        pixi run tests
