name: Full Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        manifest-path: pyproject.toml

    - name: Tests
      shell: bash -l {0}
      run: |
        pixi run tests
