name: Full Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@307e5e5842748e3752d5178fbd158e0a6c1b55ff  # v0.8.12
      with:
        manifest-path: pyproject.toml

    - name: Tests
      shell: bash -l {0}
      run: |
        pixi run tests
