name: Full Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@28eb668aafebd9dede9d97c4ba1cd9989a4d0004  # v0.9.2
      with:
        manifest-path: pyproject.toml

    - name: Tests
      shell: bash -l {0}
      run: |
        pixi run tests
