name: Full Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7  # v0.9.3
      with:
        manifest-path: pyproject.toml

    - name: Tests
      shell: bash -l {0}
      run: |
        pixi run tests
