# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create and Deploy Prod HTML site

# no permissions by default
permissions: {}

# Includes building automatically when either of the relevant JSON files update on the main branch or on the push of a button
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

  schedule:
    - cron: "0 12 1,15,28 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0  # v0.9.5
      with:
        manifest-path: pyproject.toml

    - name: create HTML file
      shell: bash -l {0}
      run: |
        pixi run build_site

    - name: Deploy 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f  # v4.8.0
      with:
        folder: website/deploy # The folder the action should deploy.
        repository-name: ioos/ioos_metrics
